In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df = pd.read_csv('geoplanet_places_7.4.0.tsv', sep='\t')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332310 entries, 0 to 5332309
Data columns (total 6 columns):
WOE_ID       int64
ISO          object
Name         object
Language     object
PlaceType    object
Parent_ID    int64
dtypes: int64(2), object(4)
memory usage: 244.1+ MB

In [8]:
df.head(100)

      WOE_ID ISO                      Name Language PlaceType  Parent_ID
0   23424994  CY  Cyprus Greek Cypriot Rep      ENG     State   26812346
1   23424995  CY               Cyprus TRNC      ENG     State   26812346
2   12577963  CY                 Famagusta      UNK    County   23424994
3   12577964  CY                   Larnaca      UNK    County   23424994
4   12577965  CY                  Limassol      UNK    County   23424994
5   12577966  CY                    Paphos      UNK    County   23424994
6   12577968  CY                 Famagusta      ENG    County   23424995
7   12577969  CY                   Kyrenia      ENG    County   23424995
8   12577971  CY                   Nicosia      ENG    County   23424995
9     841103  CY                  Akanthou      UNK      Town   12577968
10    841154  CY                      Asha      UNK      Town   12577968
11    841162  CY                  Athienou      ENG      Town   12577964
12    841163  CY                     Athna      ENG      Town   12577963
13    841179  CY                 Ayia Napa      ENG      Town   12577963
14    841188  CY           Ayios Amvrosios      UNK      Town   12577969
15    841227  CY          Ayios Theodhoros      UNK      Town   12577968
16    841248  CY                     Dhali      ENG      Town   12577966
17    841252  CY                  Dherinia      ENG      Town   12577963
18    841276  CY                  Episkopi      ENG      Town   12577965
19    841285  CY                 Famagusta      UNK      Town   12577968
20    841334  CY               Karavostasi      UNK      Town   12577971
21    841338  CY                  Kathikas      ENG      Town   12577966
22    841375  CY                Khirokitia      ENG      Town   12577964
23    841391  CY                      Kiti      ENG      Town   12577964
24    841431  CY                   Kyrenia      UNK      Town   12577969
25    841432  CY                   Kythrea      UNK      Town   12577971
26    841438  CY                  Lapithos      UNK      Town   12577969
27    841439  CY                   Larnaca      ENG      Town   12577964
28    841445  CY                     Lefka      UNK      Town   12577971
29    841446  CY                 Lefkoniko      UNK      Town   12577968
..       ...  ..                       ...      ...       ...        ...
70  12894289  CY                      2480      UNK       Zip     841546
71  12894290  CY                      2540      UNK       Zip     841711
72  12894291  CY                      2549      UNK       Zip     841711
73  12894292  CY                      2560      UNK       Zip     841546
74  12894293  CY                      2562      UNK       Zip     841711
75  12894294  CY                      2563      UNK       Zip     841711
76  12894295  CY                      2564      UNK       Zip     841546
77  12894296  CY                      2565      UNK       Zip     841546
78  12894297  CY                      2566      UNK       Zip     841711
79  12894298  CY                      2567      UNK       Zip     841711
80  12894299  CY                      2568      UNK       Zip     841546
81  12894300  CY                      2570      UNK       Zip     841711
82  12894301  CY                      2571      UNK       Zip     841711
83  12894302  CY                      2572      UNK       Zip     841711
84  12894303  CY                      2573      UNK       Zip     841711
85  12894304  CY                      2574      UNK       Zip     841711
86  12894305  CY                      2600      UNK       Zip     841546
87  12894306  CY                      2610      UNK       Zip     841546
88  12894307  CY                      2611      UNK       Zip     841546
89  12894308  CY                      2612      UNK       Zip     841546
90  12894309  CY                      2613      UNK       Zip     841546
91  12894310  CY                      2614      UNK       Zip     841546
92  12894311  CY                      2615      UNK       Zip     841546
93  12894312  CY                      2616      UNK       Zip     841546
94  12894313  CY                      2617      UNK       Zip     841546
95  12894314  CY                      2618      UNK       Zip     841546
96  12894315  CY                      2619      UNK       Zip     841546
97  12894316  CY                      2620      UNK       Zip     841546
98  12894317  CY                      2621      UNK       Zip     841546
99  12894318  CY                      2622      UNK       Zip     841546

[100 rows x 6 columns]

In [13]:
df = df[df.PlaceType != 'Zip']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1934474 entries, 0 to 5332309
Data columns (total 6 columns):
WOE_ID       int64
ISO          object
Name         object
Language     object
PlaceType    object
Parent_ID    int64
dtypes: int64(2), object(4)
memory usage: 103.3+ MB

In [16]:
df.head(100)

,WOE_ID,ISO,Name,Language,PlaceType,Parent_ID
0,23424994,CY,Cyprus Greek Cypriot Rep,ENG,State,26812346
1,23424995,CY,Cyprus TRNC,ENG,State,26812346
2,12577963,CY,Famagusta,UNK,County,23424994
3,12577964,CY,Larnaca,UNK,County,23424994
4,12577965,CY,Limassol,UNK,County,23424994
5,12577966,CY,Paphos,UNK,County,23424994
6,12577968,CY,Famagusta,ENG,County,23424995
7,12577969,CY,Kyrenia,ENG,County,23424995
8,12577971,CY,Nicosia,ENG,County,23424995
9,841103,CY,Akanthou,UNK,Town,12577968
10,841154,CY,Asha,UNK,Town,12577968
11,841162,CY,Athienou,ENG,Town,12577964
12,841163,CY,Athna,ENG,Town,12577963
13,841179,CY,Ayia Napa,ENG,Town,12577963
14,841188,CY,Ayios Amvrosios,UNK,Town,12577969
15,841227,CY,Ayios Theodhoros,UNK,Town,12577968
16,841248,CY,Dhali,ENG,Town,12577966
17,841252,CY,Dherinia,ENG,Town,12577963
18,841276,CY,Episkopi,ENG,Town,12577965
19,841285,CY,Famagusta,UNK,Town,12577968
20,841334,CY,Karavostasi,UNK,Town,12577971
21,841338,CY,Kathikas,ENG,Town,12577966
22,841375,CY,Khirokitia,ENG,Town,12577964
23,841391,CY,Kiti,ENG,Town,12577964
24,841431,CY,Kyrenia,UNK,Town,12577969
25,841432,CY,Kythrea,UNK,Town,12577971
26,841438,CY,Lapithos,UNK,Town,12577969
27,841439,CY,Larnaca,ENG,Town,12577964
28,841445,CY,Lefka,UNK,Town,12577971
29,841446,CY,Lefkoniko,UNK,Town,12577968
...,...,...,...,...,...,...
794,22500553,CY,Old Agueduct,ENG,POI,841179
795,22500567,CY,Recreation Exhibition Halls and Cinema,ENG,POI,841179
796,22500644,CY,Art Galleries & Libraries,ENG,POI,841546
797,22500652,CY,Caraffa,ENG,POI,841546
798,22500680,CY,Constanza,ENG,POI,841546
799,22500683,CY,Cyprus Archaeological Museum,ENG,POI,841546
800,22500684,CY,Cyprus Handicraft Centre,ENG,POI,841711
801,22500687,CY,Cyprus Jewellers Museum,ENG,POI,841546
802,22500688,CY,Cyprus Postal & Philatelic Museum,ENG,POI,841546
803,22500689,CY,Cyprus Struggle Museum,ENG,POI,841546
804,22500690,CY,D'Avila,ENG,POI,841546
805,22500693,CY,Dionysios Solomos Statue,ENG,POI,841546
806,22500699,CY,Famagusta Gate,ENG,POI,841546
807,22500701,CY,Filakismena Mnimata,ENG,POI,841546
808,22500702,CY,Flatro,ENG,POI,841546
809,22500704,CY,Fournoi Gallery,ENG,POI,841546
810,22500708,CY,Hadjigeorgakis Kornesios House,ENG,POI,841546
811,22500717,CY,Kastelliotissa Medieval Hall,ENG,POI,841546
812,22500718,CY,La Cava Castle,ENG,POI,841711
813,22500719,CY,Laiki Gitonia,ENG,POI,841546
814,22500723,CY,Leventis Municipal Museum,ENG,POI,841546
815,22500724,CY,Liberty Monument,ENG,POI,841546
816,22500733,CY,Markos Drakos Statue,ENG,POI,841546
817,22500735,CY,Melina Mercouri Hall,ENG,POI,841546
818,22500744,CY,Museum of Folk Art,ENG,POI,841546
819,22500745,CY,Museum of the History of Cypriot Coinage,ENG,POI,841546
820,22500758,CY,Pancyprian Geographical Museum,ENG,POI,841711
821,22500760,CY,Paphos Gate,ENG,POI,841546
822,22500787,CY,Potocataro,ENG,POI,841546
823,22500801,CY,State Collection of Contemporary Art,ENG,POI,841546

In [18]:
df[df.WOE_ID == 23424768]

           WOE_ID ISO    Name Language PlaceType  Parent_ID
3703721  23424768  BR  Brasil      POR   Country          1

In [24]:
df = df[df.PlaceType == 'Country']

In [30]:
df.head()

           WOE_ID ISO                   Name Language PlaceType  Parent_ID
57       26812346  CY                 Cyprus      ENG   Country          1
838      23424966  ST  Sao Tome and Principe      ENG   Country          1
34252    23424975  GB         United Kingdom      ENG   Country          1
1976434  23424974  UG                 Uganda      ENG   Country          1
1976928  23424805  EE                  Eesti      UNK   Country          1

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 247 entries, 57 to 5331984
Data columns (total 6 columns):
WOE_ID       247 non-null int64
ISO          246 non-null object
Name         247 non-null object
Language     247 non-null object
PlaceType    247 non-null object
Parent_ID    247 non-null int64
dtypes: int64(2), object(4)
memory usage: 13.5+ KB

In [29]:
df.to_csv('Countries_WOE_ID.csv')